_BASE_: "Base-OVD-RCNN-C4-DIOR.yaml"
MODEL:
  META_ARCHITECTURE: "CustomRCNNMViT"
  WEIGHTS: ""
  PIS_PROP_PATH: datasets/MAVL_proposals/rs_props/class_specific2
  ROI_HEADS:
    NUM_CLASSES: 123
  ROI_BOX_HEAD:
    WEIGHT_TRANSFER: False
    WS_NUM_PROPS: 32
    IMAGE_LABEL_LOSS: 'pseudo_max_score'
    ZEROSHOT_WEIGHT_PATH: "/data/pcl/object-centric-ovd/datasets/zeroshot_weights/DIOR_rs_clip_a+photo+cname.npy"

SOLVER:
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
DATASETS:
  TRAIN: ("DIOR_zeroshot_train_oriorder", "rs_pis")
INPUT:
  CUSTOM_AUG: ResizeShortestEdge
  MIN_SIZE_TRAIN_SAMPLING: range
  MIN_SIZE_TRAIN: (800, 800)
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [ 1, 4 ]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [ 2, 8 ] # Batch-size per GPU
  USE_RFS: [ False, False ]
  DATASET_MIN_SIZES: [ [ 800, 800 ], [ 400, 400 ] ]
  DATASET_MAX_SIZES: [ 1333, 667 ]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: True
  DATASET_ANN: [ 'box', 'image' ]
  NUM_WORKERS: 8
WITH_IMAGE_LABELS: True
OUTPUT_DIR: output/rs_ovd_PIS