_BASE_: "Base-OVD-RCNN-C4-DIOR.yaml"
MODEL:
  WEIGHTS: saved_models/coco_ovd_base.pth
  RKD_FEAT_PATH: datasets/MAVL_proposals/rs_dior_aggregated
  DISTILLATION: True
  DISTIL_L1_LOSS_WEIGHT: 0.15
  NUM_DISTIL_PROP: 5
  IRM_LOSS_WEIGHT: 0.15
OUTPUT_DIR: output/rs_ovd_RKD